services:
  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin --protocol=socket -uroot -p$${DB_PW} ping -S /run/mysqld/mysqld.sock || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "[ -f /var/www/html/wp-config.php ] || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 30

  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - inception
    depends_on:
      - wordpress

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/db

  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}/wp